name             'crowd_test'
maintainer       'Oregon State University'
maintainer_email 'systems@osuosl.org'
license          'Apache 2.0'
description      'Installs/Configures crowd_test'
long_description ''
version          '0.1.0'
depends          'crowd'
depends          'openssl'
